version: '2'
services:
  __serviceName__:
    build: .
    image: aldeamo/__serviceName__:__version__
    container_name: __serviceName__
    command: java -Djava.security.egd=file:/dev/./urandom -jar /home/app/__jarName__ --spring.profiles.active=__profile__
    ports:
     - "__port__:8080"
    environment:
     - "TZ=America/Bogota"
    tty: true
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /home/celuman/logs/__serviceName__:/logs/
     - /home/celuman/deployDocker/__serviceName__/Files/config:/config